[project]
name = "opencv"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "tzug1729", email = "195055595+tzug1729@users.noreply.github.com" }
]
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.5.3",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
opencv = "opencv:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"
